# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\HiTorus\Desktop\model_creation.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewModelConfiguration(object):
    def setupUi(self, NewModelConfiguration):
        NewModelConfiguration.setObjectName("NewModelConfiguration")
        NewModelConfiguration.resize(858, 489)
        NewModelConfiguration.setToolTip("")
        NewModelConfiguration.setWhatsThis("")
        NewModelConfiguration.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(NewModelConfiguration)
        self.centralwidget.setObjectName("centralwidget")
        self.embeddingGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.embeddingGroupBox.setGeometry(QtCore.QRect(10, 10, 441, 171))
        self.embeddingGroupBox.setObjectName("embeddingGroupBox")
        self.embeddingModelBrowseButton = QtWidgets.QPushButton(self.embeddingGroupBox)
        self.embeddingModelBrowseButton.setGeometry(QtCore.QRect(361, 48, 61, 21))
        self.embeddingModelBrowseButton.setObjectName("embeddingModelBrowseButton")
        self.embeddingModelLineEdit = QtWidgets.QLineEdit(self.embeddingGroupBox)
        self.embeddingModelLineEdit.setGeometry(QtCore.QRect(109, 48, 241, 20))
        self.embeddingModelLineEdit.setText("")
        self.embeddingModelLineEdit.setObjectName("embeddingModelLineEdit")
        self.vectorSizeSpinBox = QtWidgets.QDoubleSpinBox(self.embeddingGroupBox)
        self.vectorSizeSpinBox.setGeometry(QtCore.QRect(90, 124, 62, 22))
        self.vectorSizeSpinBox.setDecimals(0)
        self.vectorSizeSpinBox.setMaximum(9999.0)
        self.vectorSizeSpinBox.setProperty("value", 300.0)
        self.vectorSizeSpinBox.setObjectName("vectorSizeSpinBox")
        self.vectorSizeLabel = QtWidgets.QLabel(self.embeddingGroupBox)
        self.vectorSizeLabel.setGeometry(QtCore.QRect(20, 124, 71, 16))
        self.vectorSizeLabel.setObjectName("vectorSizeLabel")
        self.dataSetDirectoryLineEdit = QtWidgets.QLineEdit(self.embeddingGroupBox)
        self.dataSetDirectoryLineEdit.setGeometry(QtCore.QRect(109, 84, 241, 20))
        self.dataSetDirectoryLineEdit.setText("")
        self.dataSetDirectoryLineEdit.setObjectName("dataSetDirectoryLineEdit")
        self.dataSetDirectoryBrowseButton = QtWidgets.QPushButton(self.embeddingGroupBox)
        self.dataSetDirectoryBrowseButton.setGeometry(QtCore.QRect(361, 84, 61, 21))
        self.dataSetDirectoryBrowseButton.setObjectName("dataSetDirectoryBrowseButton")
        self.embeddingModelLabel = QtWidgets.QLabel(self.embeddingGroupBox)
        self.embeddingModelLabel.setGeometry(QtCore.QRect(19, 49, 121, 16))
        self.embeddingModelLabel.setObjectName("embeddingModelLabel")
        self.datasetLabel = QtWidgets.QLabel(self.embeddingGroupBox)
        self.datasetLabel.setGeometry(QtCore.QRect(20, 86, 81, 16))
        self.datasetLabel.setObjectName("datasetLabel")
        self.additionalInfoButton = QtWidgets.QPushButton(self.embeddingGroupBox)
        self.additionalInfoButton.setGeometry(QtCore.QRect(389, 123, 23, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.additionalInfoButton.setFont(font)
        self.additionalInfoButton.setObjectName("additionalInfoButton")
        self.mainModelGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mainModelGroupBox.setGeometry(QtCore.QRect(10, 183, 441, 221))
        self.mainModelGroupBox.setObjectName("mainModelGroupBox")
        self.kernelSizeLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.kernelSizeLabel.setGeometry(QtCore.QRect(55, 27, 71, 16))
        self.kernelSizeLabel.setObjectName("kernelSizeLabel")
        self.kernelSizeSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.kernelSizeSpinBox.setGeometry(QtCore.QRect(125, 27, 62, 22))
        self.kernelSizeSpinBox.setDecimals(0)
        self.kernelSizeSpinBox.setMaximum(9999.0)
        self.kernelSizeSpinBox.setProperty("value", 5.0)
        self.kernelSizeSpinBox.setObjectName("kernelSizeSpinBox")
        self.FiltersNumberSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.FiltersNumberSpinBox.setGeometry(QtCore.QRect(125, 57, 62, 22))
        self.FiltersNumberSpinBox.setDecimals(0)
        self.FiltersNumberSpinBox.setMaximum(9999.0)
        self.FiltersNumberSpinBox.setProperty("value", 200.0)
        self.FiltersNumberSpinBox.setObjectName("FiltersNumberSpinBox")
        self.filtersNumberLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.filtersNumberLabel.setGeometry(QtCore.QRect(55, 57, 71, 16))
        self.filtersNumberLabel.setObjectName("filtersNumberLabel")
        self.denseOutputLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.denseOutputLabel.setGeometry(QtCore.QRect(55, 87, 71, 16))
        self.denseOutputLabel.setObjectName("denseOutputLabel")
        self.denseOutputSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.denseOutputSpinBox.setGeometry(QtCore.QRect(125, 87, 62, 22))
        self.denseOutputSpinBox.setDecimals(0)
        self.denseOutputSpinBox.setMaximum(9999.0)
        self.denseOutputSpinBox.setProperty("value", 250.0)
        self.denseOutputSpinBox.setObjectName("denseOutputSpinBox")
        self.poolSizeSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.poolSizeSpinBox.setGeometry(QtCore.QRect(125, 117, 62, 22))
        self.poolSizeSpinBox.setDecimals(0)
        self.poolSizeSpinBox.setMaximum(9999.0)
        self.poolSizeSpinBox.setProperty("value", 1.0)
        self.poolSizeSpinBox.setObjectName("poolSizeSpinBox")
        self.poolSizeLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.poolSizeLabel.setGeometry(QtCore.QRect(55, 117, 71, 16))
        self.poolSizeLabel.setObjectName("poolSizeLabel")
        self.epochsSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.epochsSpinBox.setGeometry(QtCore.QRect(125, 147, 62, 22))
        self.epochsSpinBox.setDecimals(0)
        self.epochsSpinBox.setMaximum(9999.0)
        self.epochsSpinBox.setProperty("value", 12.0)
        self.epochsSpinBox.setObjectName("epochsSpinBox")
        self.epochsLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.epochsLabel.setGeometry(QtCore.QRect(55, 147, 71, 16))
        self.epochsLabel.setObjectName("epochsLabel")
        self.learningRateLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.learningRateLabel.setGeometry(QtCore.QRect(254, 27, 71, 16))
        self.learningRateLabel.setObjectName("learningRateLabel")
        self.learningRateSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.learningRateSpinBox.setGeometry(QtCore.QRect(324, 27, 62, 22))
        self.learningRateSpinBox.setDecimals(3)
        self.learningRateSpinBox.setMaximum(1.0)
        self.learningRateSpinBox.setProperty("value", 0.001)
        self.learningRateSpinBox.setObjectName("learningRateSpinBox")
        self.momentumLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.momentumLabel.setGeometry(QtCore.QRect(254, 57, 71, 16))
        self.momentumLabel.setObjectName("momentumLabel")
        self.momentumSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.momentumSpinBox.setGeometry(QtCore.QRect(324, 57, 62, 22))
        self.momentumSpinBox.setDecimals(1)
        self.momentumSpinBox.setMaximum(1.0)
        self.momentumSpinBox.setProperty("value", 0.9)
        self.momentumSpinBox.setObjectName("momentumSpinBox")
        self.decayLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.decayLabel.setGeometry(QtCore.QRect(254, 87, 71, 16))
        self.decayLabel.setObjectName("decayLabel")
        self.decaySpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.decaySpinBox.setGeometry(QtCore.QRect(324, 87, 62, 22))
        self.decaySpinBox.setDecimals(1)
        self.decaySpinBox.setMaximum(1.0)
        self.decaySpinBox.setProperty("value", 0.0)
        self.decaySpinBox.setObjectName("decaySpinBox")
        self.dropoutSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.dropoutSpinBox.setGeometry(QtCore.QRect(324, 117, 62, 22))
        self.dropoutSpinBox.setDecimals(1)
        self.dropoutSpinBox.setMaximum(1.0)
        self.dropoutSpinBox.setProperty("value", 0.0)
        self.dropoutSpinBox.setObjectName("dropoutSpinBox")
        self.dropoutLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.dropoutLabel.setGeometry(QtCore.QRect(254, 117, 71, 16))
        self.dropoutLabel.setObjectName("dropoutLabel")
        self.trainingValidationSlider = QtWidgets.QSlider(self.mainModelGroupBox)
        self.trainingValidationSlider.setGeometry(QtCore.QRect(150, 188, 160, 19))
        self.trainingValidationSlider.setMaximum(100)
        self.trainingValidationSlider.setSliderPosition(80)
        self.trainingValidationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trainingValidationSlider.setObjectName("trainingValidationSlider")
        self.trainingPercentageLineEdit = QtWidgets.QLineEdit(self.mainModelGroupBox)
        self.trainingPercentageLineEdit.setGeometry(QtCore.QRect(110, 186, 35, 20))
        self.trainingPercentageLineEdit.setObjectName("trainingPercentageLineEdit")
        self.validationPercentageLineEdit = QtWidgets.QLineEdit(self.mainModelGroupBox)
        self.validationPercentageLineEdit.setGeometry(QtCore.QRect(314, 186, 35, 20))
        self.validationPercentageLineEdit.setObjectName("validationPercentageLineEdit")
        self.trainingPercentageLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.trainingPercentageLabel.setGeometry(QtCore.QRect(64, 188, 47, 13))
        self.trainingPercentageLabel.setObjectName("trainingPercentageLabel")
        self.validationPercentageLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.validationPercentageLabel.setGeometry(QtCore.QRect(356, 188, 47, 13))
        self.validationPercentageLabel.setObjectName("validationPercentageLabel")
        self.saveModelButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveModelButton.setEnabled(False)
        self.saveModelButton.setGeometry(QtCore.QRect(282, 420, 130, 25))
        self.saveModelButton.setObjectName("saveModelButton")
        self.trainModelButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainModelButton.setGeometry(QtCore.QRect(49, 420, 130, 25))
        self.trainModelButton.setObjectName("trainModelButton")
        self.trainingSummaryGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.trainingSummaryGroupBox.setGeometry(QtCore.QRect(460, 10, 391, 395))
        self.trainingSummaryGroupBox.setObjectName("trainingSummaryGroupBox")
        self.trainingSummaryTextEdit = QtWidgets.QTextEdit(self.trainingSummaryGroupBox)
        self.trainingSummaryTextEdit.setGeometry(QtCore.QRect(20, 27, 351, 321))
        self.trainingSummaryTextEdit.setObjectName("trainingSummaryTextEdit")
        self.modelConfigurationBackButton = QtWidgets.QPushButton(self.centralwidget)
        self.modelConfigurationBackButton.setGeometry(QtCore.QRect(707, 420, 75, 23))
        self.modelConfigurationBackButton.setObjectName("modelConfigurationBackButton")
        NewModelConfiguration.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewModelConfiguration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menubar.setObjectName("menubar")
        NewModelConfiguration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewModelConfiguration)
        self.statusbar.setObjectName("statusbar")
        NewModelConfiguration.setStatusBar(self.statusbar)

        self.retranslateUi(NewModelConfiguration)
        QtCore.QMetaObject.connectSlotsByName(NewModelConfiguration)

    def retranslateUi(self, NewModelConfiguration):
        _translate = QtCore.QCoreApplication.translate
        NewModelConfiguration.setWindowTitle(_translate("NewModelConfiguration", "New Model Configuration"))
        self.embeddingGroupBox.setTitle(_translate("NewModelConfiguration", "Embedding"))
        self.embeddingModelBrowseButton.setText(_translate("NewModelConfiguration", "Browse"))
        self.vectorSizeLabel.setText(_translate("NewModelConfiguration", "Vector size"))
        self.dataSetDirectoryBrowseButton.setText(_translate("NewModelConfiguration", "Browse"))
        self.embeddingModelLabel.setText(_translate("NewModelConfiguration", "Embedding Model"))
        self.datasetLabel.setText(_translate("NewModelConfiguration", "Dataset Dir"))
        self.additionalInfoButton.setText(_translate("NewModelConfiguration", "?"))
        self.mainModelGroupBox.setTitle(_translate("NewModelConfiguration", "Model"))
        self.kernelSizeLabel.setText(_translate("NewModelConfiguration", "Kernel size"))
        self.filtersNumberLabel.setText(_translate("NewModelConfiguration", "Filters number"))
        self.denseOutputLabel.setText(_translate("NewModelConfiguration", "Dense output"))
        self.poolSizeLabel.setText(_translate("NewModelConfiguration", "Pool size"))
        self.epochsLabel.setText(_translate("NewModelConfiguration", "Epochs"))
        self.learningRateLabel.setText(_translate("NewModelConfiguration", "Learning rate"))
        self.momentumLabel.setText(_translate("NewModelConfiguration", "Momentum"))
        self.decayLabel.setText(_translate("NewModelConfiguration", "Decay"))
        self.dropoutLabel.setText(_translate("NewModelConfiguration", "Dropout"))
        self.trainingPercentageLineEdit.setText(_translate("NewModelConfiguration", "80%"))
        self.validationPercentageLineEdit.setText(_translate("NewModelConfiguration", "20%"))
        self.trainingPercentageLabel.setText(_translate("NewModelConfiguration", "Training"))
        self.validationPercentageLabel.setText(_translate("NewModelConfiguration", "Validation"))
        self.saveModelButton.setText(_translate("NewModelConfiguration", "Save model"))
        self.trainModelButton.setText(_translate("NewModelConfiguration", "Train"))
        self.trainingSummaryGroupBox.setTitle(_translate("NewModelConfiguration", "Training Summary"))
        self.modelConfigurationBackButton.setText(_translate("NewModelConfiguration", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewModelConfiguration = QtWidgets.QMainWindow()
    ui = Ui_NewModelConfiguration()
    ui.setupUi(NewModelConfiguration)
    NewModelConfiguration.show()
    sys.exit(app.exec_())

